const dictionary = new Map([
  [/\s?approach\s?/gi, 'วิธีการ'],
  [/\s?machine learning\s?/gi, 'การเรียนรู้ของเครื่อง'],
  [/\s?big data\s?/gi, 'ข้อมูลมหัต'],
  [/\s?coding\s?/gi, 'การกำหนดรหัส'],
  [/\s?joystick\s?/gi, 'แท่งหรรษา'],
  [/\s?subscriber\s?/gi, 'ผู้รับบริการ'],
  [/\s?flash mob\s?/gi, 'ม็อบฉับพลัน'],
  [/\s?red ocean\s?/gi, 'มหาสมุทรสีชาด'],
  [/\s?blue ocean\s?/gi, 'มหาสมุทรสีคราม'],
  [/\s?communicate\s?/gi, 'สื่อสาร'],
  [/\s?computer\s?/gi, 'คณิตกรณ์'],
  [/\s?subscriber\s?/gi, 'ผู้รับบริการ'],
  [/\s?vlog\s?/gi, 'วล็อก'],
  [/\s?mindset\s?/gi, 'กรอบคิดติดยึด'],
  [/\s?system analysis\s?/gi, 'การวิเคราะห์ระบบ'],
  [/\s?input\s?/gi, 'ปัจจัยป้อนเข้า'],
  [/\s?goal\s?/gi, 'เป้าประสงค์'],
  [/\s?aim\s?/gi, 'จุดหมาย'],
  [/\s?conflict of interest\s?/gi, 'การขัดกันแห่งผลประโยชน์'],
  [/\s?strengths analysis\s?/gi, 'การวิเคราะห์จุดแข็ง'],
  [/\s?weaknesses analysis\s?/gi, 'การวิเคราะห์จุดอ่อน'],
  [/\s?inequality\s?/gi, 'ความเหลื่อมล้ำ'],
  [/\s?cheat day\s?/gi, 'วันตามใจปาก'],
  [/\s?breaking news\s?/gi, 'ข่าวแทรก'],
  [/\s?flash news\s?/gi, 'ข่าวด่วน'],
  [/\s?artificial intelligence\s?/gi, 'ปัญญาประดิษฐ์'],
  [/\s?AI\s?/gi, 'ปัญญาประดิษฐ์'],
  [/\s?limit\s?/gi, 'ขอบเขต'],
  [/\s?side effect\s?/gi, 'ผลข้างเคียง'],
  [/\s?e-banking\s?/gi, 'ธนาคารอิเล็กทรอนิกส์'],
  [/\s?academic integrity\s?/gi, 'ความซื่อตรงทางวิชาการ'],
  [/\s?coaching\s?/gi, 'การชี้แนะ'],
  [/\s?coding\s?/gi, 'การลงรหัส'],
  [/\s?media platform\s?/gi, 'ฐานช่องทางสื่อ'],
  [/\s?blog\s?/gi, 'บล็อก'],
  [/\s?dominate\s?/gi, 'การฝึกหัด'],
  [/\s?introvert\s?/gi, 'คนเก็บตัว'],
  [/\s?extrovert\s?/gi, 'คนพาหิรวัฒน์'],
  [/\s?handle\s?/gi, 'รับ'],
  [/\s?group influence\s?/gi, 'อิทธิพลของกลุ่ม'],
  [/\s?counter example\s?/gi, 'ตัวอย่างค้าน'],
  [/\s?deep learning\s?/gi, 'การเรียนรู้เชิงลึก'],
  [/\s?growth mindset\s?/gi, 'กรอบคิดติดยึดเติบโต '],
  [/\s?fixed mindset\s?/gi, 'กรอบยึดติดฝังแน่น'],
  [/\s?normalize\s?/gi, 'ทำให้เป็นบรรทัดฐาน'],
  [/\s?pedophilia\s?/gi, 'โรคใครเด็ก'],
  [/\s?agenda\s?/gi, 'ระเบียบวาระการประชุม'],
  [/\s?taboo\s?/gi, 'ข้อห้าม'],
  [/\s?reaction\s?/gi, 'ปฎิกิริยา'],
  [/\s?digital disruption\s?/gi, 'การเปลี่ยนฉับพลันทางดิจิทัล'],
  [/\s?online conference\s?/gi, 'การประชุมออนไลน์'],
  [/\s?new normal\s?/gi, 'ปกติใหม่'],
  [/\s?disruptor\s?/gi, 'ผู้เปลี่ยนฉับพลัน'],
  [/\s?globalization\s?/gi, 'โลกาภิวัตน์'],
  [/\s?social media\s?/gi, 'สื่อสังคม'],
  [/\s?social network\s?/gi, 'เครือข่ายสังคม'],
  [/\s?empathy\s?/gi, 'ความร่วมรู้สึก'],
  [/\s?sympathy\s?/gi, 'ความเห็นอกเห็นใจ'],
  [/\s?self awareness\s?/gi, 'การตระหนักรู้ในตัวเอง'],
  [/\s?egocentric\s?/gi, 'การยกอัตตา'],
  [/\s?cyberbullying\s?/gi, 'การระรานทางไซเบอร์'],
  [/\s?cybersecurity\s?/gi, 'ความมั่นคงปลอดภัยทางไซเบอร์'],
  [/\s?cyber crime\s?/gi, 'อาชญากรรมไซเบอร์'],
  [/\s?augmented reality\s?/gi, 'ความเป็นจริงเสริม'],
  [/\s?AR\s?/gi, 'เออาร์'],
  [/\s?bitcoin\s?/gi, 'บิตคอยน์'],
  [/\s?blockchain\s?/gi, 'บล็อกเชน'],
  [/\s?cryptocurrency\s?/gi, 'เงินตราเข้ารหัสลับ'],
  [/\s?data analytics\s?/gi, 'วิทยาการวิเคราะห์ข้อมูล'],
  [/\s?data science\s?/gi, 'วิทยาการข้อมูล'],
  [/\s?digital literacy\s?/gi, 'การรู้ดิจิตัล'],
  [/\s?digital transformation\s?/gi, 'การแปลงเป็นดิจิตัล'],
  [/\s?fourth generation\s?/gi, 'ยุคที่สี่'],
  [/\s?4G\s?/gi, 'สี่จี'],
  [/\s?fifth generation\s?/gi, 'ยุคที่ห้า'],
  [/\s?5G\s?/gi, 'ห้าจี'],
  [/\s?infographics\s?/gi, 'อินโฟกราฟิกส์'],
  [/\s?phishing\s?/gi, 'ฟิชชิง'],
  [/\s?unmanned aerial vehicle\s?/gi, 'อากาศยานไร้คนขับ'],
  [/\s?UAV\s?/gi, 'ยูเอวี'],
  [/\s?virtual reality\s?/gi, 'ความเป็นจริงเสมอ'],
  [/\s?VR\s?/gi, 'วีอาร์'],
  [/\s?data\s?/gi, 'ข้อมูล'],
  [/\s?data visualization\s?/gi, 'การนำเสนอภาพข้อมูล'],
  [/\s?partner\s?/gi, 'หุ้นส่วน'],
  [/\s?export\s?/gi, 'ส่งออก'],
  [/\s?import\s?/gi, 'นำเข้า'],
  [/\s?data source\s?/gi, 'แหล่งข้อมูล'],
  [/\s?sign in\s?/gi, 'เข้าสู่ระบบ'],
  [/\s?layout\s?/gi, 'แบบการจัดหน้า'],
  [/\s?theme\s?/gi, 'แก่นเรื่อง'],
  [/\s?report\s?/gi, 'รายงาน'],
  [/\s?pattern\s?/gi, 'รูปแบบ'],
  [/\s?user\s?/gi, 'ผู้ใช้'],
  [/\s?experiment\s?/gi, 'การทดลอง'],
  [/\s?bias\s?/gi, 'อคติ'],
  [/\s?label\s?/gi, 'แปะป้าย'],
  [/\s?direction\s?/gi, 'ทิศทาง'],
  [/\s?data set\s?/gi, 'ชุดข้อมูล'],
  [/\s?curve\s?/gi, 'เส้นโค้ง'],
  [/\s?quarantine\s?/gi, 'การกักด่าน'],
  [/\s?public services\s?/gi, 'การบริการสาธารณะ'],
  [/\s?validation\s?/gi, 'การให้เหตุผล'],
  [/\s?observation\s?/gi, 'การสังเกตการณ์'],
  [/\s?observer\s?/gi, 'ผู้สังเกตการณ์'],
  [/\s?natural selection\s?/gi, 'การคัดเลือกตามธรรมชาติ'],
  [/\s?questionnaire\s?/gi, 'แบบสอบถาม'],
  [/\s?tone\s?/gi, 'น้ำเสียง'],
  [/\s?text\s?/gi, 'ข้อความ'],
  [/\s?open source\s?/gi, 'โอเพนซอร์ซ'],
  [/\s?startup\s?/gi, 'บริษัทจัดตั้งใหม่'],
  [/\s?objective\s?/gi, 'วัตถุวิสัย'],
  [/\s?reasoning\s?/gi, 'การให้เหตุผล'],
  [/\s?hackathon\s?/gi, 'แฮกกาธอน'],
  [/\s?argument\s?/gi, 'ข้อโต้แย้ง'],
  [/\s?statement\s?/gi, 'แถลงการณ์'],
  [/\s?perspective\s?/gi, 'มุมมอง'],
  [/\s?interdisciplinary\s?/gi, ''],
  [/\s?subtext\s?/gi, 'ความนัย'],
  [/\s?provocative\s?/gi, 'เร้าใจ'],
  [/\s?offensive\s?/gi, 'การรุก'],
  [/\s?gender equality\s?/gi, 'ความเท่าเทียมทางเพศ'],
  [/\s?gender oppression\s?/gi, 'การแสดงออกทางเพศ'],
  [/\s?disclaimer\s?/gi, 'คำปฏิเสธ'],
  [/\s?myth\s?/gi, 'ตำนาน'],
  [/\s?fact\s?/gi, 'ความจริง'],
  [/\s?sexual harassment\s?/gi, 'การคุกคามทางเพศ'],
  [/\s?child abusing\s?/gi, 'การทารุณกรรมเด็ก'],
  [/\s?framework\s?/gi, 'การพัฒนาระบบพื้นฐาน'],
  [/\s?unproductive\s?/gi, 'ไม่ก่อผล'],
  [/\s?make fun\s?/gi, 'ทำให้เป็นเรื่องสนุก'],
  [/\s?toxic\s?/gi, 'พิษ'],
  [/\s?process\s?/gi, 'กระบวนการ'],
  [/\s?comfort zone\s?/gi, 'พื้นที่'],
  [/\s?rape\s?/gi, 'การข่มขืนกระทำชำเรา'],
  [/\s?speak out\s?/gi, 'พูดเสียงดัง'],
  [/\s?live\s?/gi, 'ถ่ายทอดสด'],
  [/\s?subjective\s?/gi, 'อัตนัย'],
  [/\s?movement\s?/gi, 'การเคลื่อนไหว'],
  [/\s?mental health\s?/gi, 'สุขภาพจิต'],
  [/\s?deadline\s?/gi, 'เส้นตาย'],
  [/\s?motivation\s?/gi, 'แรงกระตุ้น'],
  [/\s?motivate\s?/gi, 'กระตุ้น'],
  [/\s?inspiration\s?/gi, 'แรงบันดาลใจ'],
  [/\s?software\s?/gi, 'ละมุนภัณฑ์'],
  [/\s?hardware\s?/gi, 'กระด้างภัณฑ์'],
]);

export default dictionary;
